---

- name: "RUN DATA VALIDATION CHECKS"
  hosts: "all"
  connection: "local"
  gather_facts: "no"

  tasks:
    - name: "INCLUDE ANY CHECK IN FOLDER"
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: "outer_item"
      with_fileglob:
        - "{{ playbook_dir }}/offline_data_checks/*"
